/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoRouteImport } from './routes/go'
import { Route as OgRouteImport } from './routes/og'
import { Route as ApiRunRouteImport } from './routes/api/run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunRoute = ApiRunRouteImport.update({
  id: '/api/run',
  path: '/api/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/go': typeof GoRoute
  '/og': typeof OgRoute
  '/api/run': typeof ApiRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/go': typeof GoRoute
  '/og': typeof OgRoute
  '/api/run': typeof ApiRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/go': typeof GoRoute
  '/og': typeof OgRoute
  '/api/run': typeof ApiRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/go' | '/og' | '/api/run'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/go' | '/og' | '/api/run'
  id: '__root__' | '/' | '/go' | '/og' | '/api/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoRoute: typeof GoRoute
  OgRoute: typeof OgRoute
  ApiRunRoute: typeof ApiRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run': {
      id: '/api/run'
      path: '/api/run'
      fullPath: '/api/run'
      preLoaderRoute: typeof ApiRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoRoute: GoRoute,
  OgRoute: OgRoute,
  ApiRunRoute: ApiRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
